export const ingredients = [
    "salt",
    "sugar",
    "butter",
    "black pepper",
    "onion",
    "eggs",
    "all-purpose flour",
    "water",
    "olive oil",
    "pepper",
    "milk",
    "garlic cloves",
    "unsalted butter",
    "vegetable oil",
    "extra-virgin olive oil",
    "brown sugar",
    "baking powder",
    "lemon juice",
    "vanilla extract",
    "freshly ground pepper",
    "carrots",
    "cloves garlic",
    "flour",
    "baking soda",
    "tomatoes",
    "kosher salt",
    "ground cinnamon",
    "green onions",
    "large eggs",
    "vanilla",
    "sour cream",
    "honey",
    "cream cheese",
    "granulated sugar",
    "red onion",
    "chicken broth",
    "fresh parsley",
    "garlic powder",
    "cornstarch",
    "oil",
    "grated parmesan cheese",
    "minced garlic",
    "white sugar",
    "mayonnaise",
    "ground cumin",
    "soy sauce",
    "fresh lemon juice",
    "heavy cream",
    "cinnamon",
    "margarine",
    "celery",
    "paprika",
    "shallots",
    "fresh cilantro",
    "potatoes",
    "chili powder",
    "worcestershire sauce",
    "red bell pepper",
    "canola oil",
    "dijon mustard",
    "egg whites",
    "bacon",
    "powdered sugar",
    "lemon",
    "orange juice",
    "dried oregano",
    "scallions",
    "shredded cheddar cheese",
    "cooking spray",
    "cayenne pepper",
    "ground beef",
    "sea salt",
    "shrimp",
    "diced tomatoes",
    "strawberries",
    "melted butter",
    "spinach",
    "ground nutmeg",
    "zucchini",
    "egg yolks",
    "fresh basil",
    "garlic",
    "dry white wine",
    "balsamic vinegar",
    "parmesan cheese",
    "juice",
    "apples",
    "chopped walnuts",
    "ground ginger",
    "semisweet chocolate",
    "chopped pecans",
    "chicken stock",
    "buttermilk",
    "chicken",
    "fresh ginger",
    "light brown sugar",
    "lime juice",
    "red pepper",
    "chicken breasts",
    "raisins",
    "red wine vinegar",
    "whipped cream",
    "cheese",
    "cream",
    "green pepper",
    "green bell pepper",
    "mushrooms",
    "softened butter",
    "dried thyme",
    "icing",
    "ice",
    "corn",
    "coarse salt",
    "shortening",
    "bananas",
    "beaten eggs",
    "fresh lime juice",
    "breadcrumbs",
    "fresh rosemary",
    "cider vinegar",
    "chopped celery",
    "cheddar cheese",
    "parsley",
    "raspberries",
    "finely chopped onion",
    "crushed red pepper",
    "orange",
    "tomato paste",
    "lime",
    "cucumber",
    "rice",
    "avocado",
    "chives",
    "bay leaf",
    "half & half",
    "half and half",
    "fresh thyme",
    "ground pepper",
    "flour tortillas",
    "ketchup",
    "confectioners sugar",
    "bread crumbs",
    "green beans",
    "curry powder",
    "red pepper flakes",
    "ground cloves",
    "lemon zest",
    "cold water",
    "black beans",
    "tomato sauce",
    "salsa",
    "plum tomatoes",
    "sesame oil",
    "lemon peel",
    "sweet potatoes",
    "flat leaf parsley",
    "ginger",
    "boiling water",
    "asparagus",
    "bay leaves",
    "boneless skinless chicken breasts",
    "pineapple",
    "chopped parsley",
    "blueberries",
    "whole milk",
    "feta cheese",
    "cherry tomatoes",
    "nutmeg",
    "lean ground beef",
    "dried basil",
    "sage",
    "shredded mozzarella cheese",
    "mustard",
    "ham",
    "jalapeno pepper",
    "maple syrup",
    "sweet pepper",
    "oregano",
    "almond extract",
    "onion powder",
    "peanuts",
    "sliced mushrooms",
    "pecans",
    "pasta",
    "vinegar",
    "cornmeal",
    "basil leaves",
    "hot pepper sauce",
    "broccoli",
    "pure vanilla extract",
    "active dry yeast",
    "whole wheat flour",
    "peaches",
    "beef broth",
    "white wine vinegar",
    "hot sauce",
    "dry mustard",
    "dark brown sugar",
    "swiss cheese",
    "fresh dill",
    "thyme leaves",
    "reduced sodium chicken broth",
    "food coloring",
    "chopped cilantro",
    "orange peel",
    "fresh mint",
    "celery ribs",
    "bell pepper",
    "cranberries",
    "sliced almonds",
    "vegetables",
    "mango",
    "picante sauce",
    "orange zest",
    "diced onion",
    "bread",
    "broccoli florets",
    "cumin",
    "boneless chicken breast",
    "beef",
    "mozzarella cheese",
    "sesame seeds",
    "flaked coconut",
    "fresh oregano",
    "fresh basil leaves",
    "rice vinegar",
    "ground allspice",
    "molasses",
    "ground red pepper",
    "ground coriander",
    "bittersweet chocolate",
    "almonds",
    "cocoa powder",
    "vanilla ice cream",
    "dried cranberries",
    "frozen peas",
    "basil",
    "sweet onion",
    "peanut butter",
    "eggplant",
    "tsp",
    "black olives",
    "heavy whipping cream",
    "sharp cheddar cheese",
    "sweetened condensed milk",
    "garlic salt",
    "rolled oats",
    "white pepper",
    "chocolate chips",
    "cream of tartar",
    "pine nuts",
    "evaporated milk",
    "white onion",
    "condensed cream",
    "light corn syrup",
    "plain yogurt",
    "spaghetti",
    "ricotta cheese",
    "chocolate",
    "hot water",
    "vegetable broth",
    "chopped fresh thyme",
    "pumpkin",
    "pears",
    "nonstick cooking spray",
    "semisweet chocolate chips",
    "whipped topping",
    "cream of mushroom soup",
    "pork tenderloin",
    "barbecue sauce",
    "cilantro leaves",
    "artichoke hearts",
    "cayenne",
    "cocoa",
    "stick butter",
    "cilantro",
    "sausage",
    "boneless skinless chicken",
    "jalapeno",
    "cake mix",
    "dry red wine",
    "seasoning salt",
    "goat cheese",
    "cake flour",
    "turkey",
    "freshly grated parmesan",
    "coconut",
    "unsweetened chocolate",
    "kalamata olives",
    "mint",
    "cinnamon sticks",
    "tarragon",
    "nuts",
    "black peppercorns",
    "egg noodles",
    "beer",
    "rosemary",
    "grated nutmeg",
    "vodka",
    "arugula",
    "chopped fresh chives",
    "peanut oil",
    "pineapple juice",
    "minced onion",
    "kidney beans",
    "peeled fresh ginger",
    "ground turkey",
    "pork chops",
    "red wine",
    "coconut milk",
    "golden raisins",
    "white bread",
    "shredded monterey jack cheese",
    "grated lemon zest",
    "chilies",
    "brandy",
    "brown rice",
    "gelatin",
    "crabmeat",
    "mint leaves",
    "reduced-fat sour cream",
    "cream of chicken soup",
    "sundried tomatoes",
    "sun-dried tomatoes",
    "grated orange",
    "prosciutto",
    "coriander",
    "cumin seed",
    "tortilla chips",
    "crushed tomatoes",
    "olives",
    "peas",
    "salad dressing",
    "fruit",
    "butternut squash",
    "fennel seeds",
    "french bread",
    "chicken thighs",
    "marshmallows",
    "cherries",
    "apple juice",
    "parmigiano-reggiano",
    "candy",
    "pistachio",
    "herbs",
    "ground white pepper",
    "bread flour",
    "fresh orange juice",
    "turmeric",
    "chopped fresh mint",
    "condensed cream of mushroom soup",
    "cabbage",
    "vanilla bean",
    "lemon rind",
    "radishes",
    "whole cloves",
    "tuna",
    "marjoram",
    "baking potatoes",
    "prepared mustard",
    "creamy peanut butter",
    "monterey jack cheese",
    "gingerroot",
    "dijon",
    "apple cider",
    "parmesan",
    "hazelnuts",
    "reduced sodium soy sauce",
    "chickpeas",
    "cauliflower"
  ]